'use client';

import { AlertTriangle } from 'lucide-react';
import { cn } from '@/lib/utils';

interface DisclaimerProps {
  variant?: 'banner' | 'inline' | 'compact';
  className?: string;
}

const DISCLAIMER_TEXT =
  'IMPORTANT: This report is generated by artificial intelligence and is intended for informational and educational purposes only. It does not constitute legal, financial, or real estate advice. All contract templates and documents must be reviewed and approved by a licensed real estate attorney in your state before execution. ListAI is not a licensed real estate broker, agent, or attorney and does not represent buyers or sellers in any transaction. Real estate transactions involve complex legal requirements — please consult a licensed professional before proceeding.';

export default function Disclaimer({ variant = 'banner', className }: DisclaimerProps) {
  if (variant === 'banner') {
    return (
      <div
        className={cn(
          'w-full bg-amber-50 border border-amber-200 rounded-lg p-4 md:p-5',
          className
        )}
      >
        <div className="flex items-start gap-3">
          <AlertTriangle className="h-5 w-5 text-amber-600 mt-0.5 flex-shrink-0" />
          <p className="text-sm text-amber-900 leading-relaxed font-medium">
            {DISCLAIMER_TEXT}
          </p>
        </div>
      </div>
    );
  }

  if (variant === 'inline') {
    return (
      <div
        className={cn(
          'border-l-4 border-amber-300 bg-amber-50/50 pl-4 py-3 pr-3 rounded-r-md',
          className
        )}
      >
        <div className="flex items-start gap-2">
          <AlertTriangle className="h-4 w-4 text-amber-500 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-amber-800 leading-relaxed">
            {DISCLAIMER_TEXT}
          </p>
        </div>
      </div>
    );
  }

  // compact
  return (
    <p className={cn('text-[11px] text-slate-500 leading-relaxed', className)}>
      {DISCLAIMER_TEXT}
    </p>
  );
}
