import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="bg-navy-800 text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="col-span-1 md:col-span-2">
            <div className="flex items-center gap-2.5 mb-4">
              <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect width="32" height="32" rx="8" fill="white" fillOpacity="0.1"/>
                <path d="M7 16L16 8L25 16" stroke="#3B82F6" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                <path d="M10 16V23H22V16" stroke="white" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"/>
                <rect x="14" y="18" width="4" height="5" rx="1" fill="#3B82F6"/>
              </svg>
              <span className="text-xl font-bold">
                List<span className="text-blue-400">AI</span>
              </span>
            </div>
            <p className="text-slate-400 text-sm max-w-md">
              AI-powered home selling toolkit for homeowners and real
              estate agents. Pricing analysis, listing copy, timeline, and legal
              templates — all in one report.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-sm mb-3">Product</h4>
            <ul className="space-y-2 text-sm text-slate-400">
              <li>
                <Link href="/homeowner" className="hover:text-white transition-colors">
                  For Homeowners
                </Link>
              </li>
              <li>
                <Link href="/agent" className="hover:text-white transition-colors">
                  For Agents
                </Link>
              </li>
              <li>
                <Link href="/dashboard" className="hover:text-white transition-colors">
                  Agent Dashboard
                </Link>
              </li>
            </ul>
          </div>

          <div>
            <h4 className="font-semibold text-sm mb-3">Support</h4>
            <ul className="space-y-2 text-sm text-slate-400">
              <li>
                <a href="mailto:hello@listwithai.io" className="hover:text-white transition-colors">
                  hello@listwithai.io
                </a>
              </li>
              <li>
                <Link href="/privacy" className="hover:text-white transition-colors">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/terms" className="hover:text-white transition-colors">
                  Terms of Service
                </Link>
              </li>
              <li>
                <Link href="/disclaimer" className="hover:text-white transition-colors">
                  Disclaimer
                </Link>
              </li>
              <li>
                <Link href="/refund-policy" className="hover:text-white transition-colors">
                  Refund Policy
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-10 pt-8 border-t border-slate-700">
          <p className="text-xs text-slate-500 leading-relaxed">
            IMPORTANT: This product is generated by artificial intelligence and
            is intended for informational and educational purposes only. It does
            not constitute legal, financial, or real estate advice. ListAI is not
            a licensed real estate broker, agent, or attorney and does not
            represent buyers or sellers in any transaction. Real estate
            transactions involve complex legal requirements — please consult a
            licensed professional before proceeding.
          </p>
          <p className="text-xs text-slate-500 mt-4">
            &copy; {new Date().getFullYear()} ListAI. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}
