import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="bg-navy-800 text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="col-span-1 md:col-span-2">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 bg-white rounded-lg flex items-center justify-center">
                <span className="text-navy-800 font-bold text-sm">L</span>
              </div>
              <span className="text-xl font-bold">
                List<span className="text-blue-400">AI</span>
              </span>
            </div>
            <p className="text-slate-400 text-sm max-w-md">
              AI-powered home selling toolkit for Florida homeowners and real
              estate agents. Pricing analysis, listing copy, timeline, and legal
              templates — all in one report.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-sm mb-3">Product</h4>
            <ul className="space-y-2 text-sm text-slate-400">
              <li>
                <Link href="/homeowner" className="hover:text-white transition-colors">
                  For Homeowners
                </Link>
              </li>
              <li>
                <Link href="/agent" className="hover:text-white transition-colors">
                  For Agents
                </Link>
              </li>
              <li>
                <Link href="/dashboard" className="hover:text-white transition-colors">
                  Agent Dashboard
                </Link>
              </li>
            </ul>
          </div>

          <div>
            <h4 className="font-semibold text-sm mb-3">Support</h4>
            <ul className="space-y-2 text-sm text-slate-400">
              <li>
                <a href="mailto:support@listwithai.io" className="hover:text-white transition-colors">
                  support@listwithai.io
                </a>
              </li>
              <li>
                <span className="cursor-default">Privacy Policy</span>
              </li>
              <li>
                <span className="cursor-default">Terms of Service</span>
              </li>
              <li>
                <span className="cursor-default">Disclaimer</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-10 pt-8 border-t border-slate-700">
          <p className="text-xs text-slate-500 leading-relaxed">
            IMPORTANT: This product is generated by artificial intelligence and
            is intended for informational and educational purposes only. It does
            not constitute legal, financial, or real estate advice. ListAI is not
            a licensed real estate broker, agent, or attorney and does not
            represent buyers or sellers in any transaction. Florida real estate
            transactions involve complex legal requirements — please consult a
            licensed professional before proceeding.
          </p>
          <p className="text-xs text-slate-500 mt-4">
            &copy; {new Date().getFullYear()} ListAI. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}
