import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — ListAI',
  description: 'Terms and conditions for using ListAI services.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <Link
          href="/"
          className="text-sm text-slate-500 hover:text-slate-900 transition-colors mb-8 inline-block"
        >
          &larr; Back to ListAI
        </Link>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: March 16, 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-700 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using ListAI (&quot;the Service&quot;) at listwithai.io, you agree
              to be bound by these Terms of Service. If you do not agree to these terms, do not
              use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">2. Description of Service</h2>
            <p>
              ListAI provides AI-generated home selling reports for Florida properties. Our
              reports include pricing analysis, listing copy, selling timeline, home improvement
              recommendations, and legal document templates. Reports are generated using
              artificial intelligence and third-party data sources.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">3. Not Professional Advice</h2>
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
              <p className="font-semibold text-amber-900 mb-2">Important Disclaimer</p>
              <p className="text-amber-800 text-sm">
                ListAI is <strong>NOT</strong> a licensed real estate broker, agent, appraiser,
                or attorney. Our reports are generated by artificial intelligence and are for
                <strong> informational and educational purposes only</strong>. They do not
                constitute legal, financial, real estate, or tax advice. You should consult with
                licensed professionals (real estate attorney, licensed appraiser, CPA, etc.)
                before making any decisions related to buying or selling real property.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">4. Pricing & Payment</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Homeowner Report</strong> — $500 one-time payment per property report.
              </li>
              <li>
                <strong>Agent Subscription</strong> — $150/month recurring subscription for
                unlimited reports and dashboard access.
              </li>
              <li>
                All payments are processed securely through Stripe. Prices are in U.S. dollars
                and are subject to change with notice.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">5. Refund Policy</h2>
            <p>
              Please see our{' '}
              <Link href="/refund-policy" className="text-blue-600 hover:underline">
                Refund Policy
              </Link>{' '}
              for details on refunds, cancellations, and our satisfaction guarantee.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">6. Accuracy of Information</h2>
            <p>
              While we strive to provide accurate and helpful information, ListAI does not
              guarantee the accuracy, completeness, or reliability of any AI-generated content,
              property valuations, comparable sales data, or legal templates. Market conditions
              change rapidly, and AI models may produce errors. Always verify critical
              information independently.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">7. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Provide accurate property and contact information.</li>
              <li>Use reports for lawful purposes only.</li>
              <li>Not resell, redistribute, or publicly display reports without permission.</li>
              <li>Consult licensed professionals before acting on report content.</li>
              <li>
                Have legal templates reviewed by a Florida-licensed real estate attorney before
                use in any transaction.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">8. Intellectual Property</h2>
            <p>
              The ListAI website, branding, and underlying technology are owned by ListAI. Upon
              purchase, you receive a personal, non-transferable license to use your generated
              report for the stated property. You may not reproduce, distribute, or create
              derivative works from our platform or technology.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, ListAI and its operators shall not be
              liable for any indirect, incidental, special, consequential, or punitive damages,
              including but not limited to loss of profits, property value, or data, arising
              from your use of the Service. Our total liability shall not exceed the amount you
              paid for the specific report or subscription in question.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless ListAI, its operators, and affiliates
              from any claims, losses, or damages arising from your use of the Service,
              including any reliance on AI-generated content without independent professional
              verification.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">11. Florida Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              State of Florida, without regard to conflict of law principles. Any disputes shall
              be resolved in the state or federal courts located in Florida.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">12. Modifications</h2>
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the
              Service after changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">13. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:evangelos@univentureprop.com" className="text-blue-600 hover:underline">
                evangelos@univentureprop.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
