/**
 * Email templates for the 5-stage followup sequence.
 * Each stage returns { subject, html } with inline-styled HTML.
 */

const BRAND_NAVY = '#0F172A';
const BRAND_SLATE = '#334155';
const BRAND_LIGHT = '#F8FAFC';
const BRAND_ACCENT = '#3B82F6';

const DISCLAIMER_TEXT =
  'IMPORTANT: This report is generated by artificial intelligence and is intended for informational and educational purposes only. It does not constitute legal, financial, or real estate advice. All contract templates and documents must be reviewed and approved by a licensed real estate attorney in your state before execution. ListAI is not a licensed real estate broker, agent, or attorney and does not represent buyers or sellers in any transaction. Real estate transactions involve complex legal requirements — please consult a licensed professional before proceeding.';

function emailWrapper(content: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:${BRAND_LIGHT};font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen,Ubuntu,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:${BRAND_LIGHT};">
    <tr><td align="center" style="padding:40px 16px;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#FFFFFF;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
        <!-- Header -->
        <tr><td style="background-color:${BRAND_NAVY};padding:24px 32px;">
          <h1 style="margin:0;color:#FFFFFF;font-size:22px;font-weight:700;letter-spacing:-0.02em;">ListAI</h1>
          <p style="margin:4px 0 0;color:#94A3B8;font-size:13px;">Your AI-Powered Home Sale Assistant</p>
        </td></tr>
        <!-- Body -->
        <tr><td style="padding:32px;">
          ${content}
        </td></tr>
        <!-- Footer -->
        <tr><td style="padding:24px 32px;background-color:#F1F5F9;border-top:1px solid #E2E8F0;">
          <p style="margin:0 0 12px;color:#64748B;font-size:11px;line-height:1.5;">${DISCLAIMER_TEXT}</p>
          <p style="margin:0;color:#94A3B8;font-size:11px;">&copy; ${new Date().getFullYear()} ListAI. All rights reserved.</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function button(text: string, href: string): string {
  return `<a href="${href}" style="display:inline-block;padding:12px 28px;background-color:${BRAND_NAVY};color:#FFFFFF;text-decoration:none;border-radius:8px;font-size:14px;font-weight:600;margin:8px 4px;">${text}</a>`;
}

function secondaryButton(text: string, href: string): string {
  return `<a href="${href}" style="display:inline-block;padding:12px 28px;background-color:#FFFFFF;color:${BRAND_NAVY};text-decoration:none;border-radius:8px;font-size:14px;font-weight:600;border:2px solid ${BRAND_NAVY};margin:8px 4px;">${text}</a>`;
}

interface EmailResult {
  subject: string;
  html: string;
}

/**
 * Returns the subject and HTML body for a given followup stage.
 *
 * Stage 1 — Day 3: MLS checklist with Houzeo/ListWithFreedom links
 * Stage 2 — Day 14: Offer evaluation tips
 * Stage 3 — Day 30: Check-in with sold/still active CTAs
 * Stage 4 — Day 45: Price adjustment offer
 * Stage 5 — Day 60 (only if sold): Referral request
 */
export function getFollowupEmail(
  stage: number,
  name: string,
  reportId: string,
  appUrl: string
): EmailResult {
  const firstName = name.split(' ')[0] || name;

  switch (stage) {
    case 1:
      return stage1(firstName, reportId, appUrl);
    case 2:
      return stage2(firstName, reportId, appUrl);
    case 3:
      return stage3(firstName, reportId, appUrl);
    case 4:
      return stage4(firstName, reportId, appUrl);
    case 5:
      return stage5(firstName, reportId, appUrl);
    default:
      throw new Error(`Unknown followup stage: ${stage}`);
  }
}

// ─── Stage 1 — Day 3: MLS Checklist ─────────────────────────────────────────

function stage1(name: string, reportId: string, appUrl: string): EmailResult {
  return {
    subject: `${name}, your MLS listing checklist is ready`,
    html: emailWrapper(`
      <h2 style="margin:0 0 16px;color:${BRAND_NAVY};font-size:20px;">Ready to get on the MLS?</h2>
      <p style="margin:0 0 16px;color:${BRAND_SLATE};font-size:15px;line-height:1.6;">
        Hi ${name}, now that you have your ListAI report, the next step is getting your property live on the MLS
        so buyers and their agents can find it. Here's your checklist:
      </p>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 20px;">
        <tr><td style="padding:8px 0;color:${BRAND_SLATE};font-size:14px;line-height:1.5;">&#9745; Professional photos taken (phone is OK to start, but pro photos sell faster)</td></tr>
        <tr><td style="padding:8px 0;color:${BRAND_SLATE};font-size:14px;line-height:1.5;">&#9745; Property description finalized (check your report's Listing Copy module)</td></tr>
        <tr><td style="padding:8px 0;color:${BRAND_SLATE};font-size:14px;line-height:1.5;">&#9745; Seller's Disclosure form completed</td></tr>
        <tr><td style="padding:8px 0;color:${BRAND_SLATE};font-size:14px;line-height:1.5;">&#9745; Choose a flat-fee MLS service &amp; submit your listing</td></tr>
        <tr><td style="padding:8px 0;color:${BRAND_SLATE};font-size:14px;line-height:1.5;">&#9745; Set up showing instructions (lockbox or by appointment)</td></tr>
      </table>
      <p style="margin:0 0 8px;color:${BRAND_SLATE};font-size:15px;font-weight:600;">
        We recommend these flat-fee MLS services:
      </p>
      <p style="margin:0 0 24px;color:${BRAND_SLATE};font-size:14px;line-height:1.6;">
        Both get your listing on the MLS, Zillow, Realtor.com, and Redfin for under $300.
      </p>
      <div style="text-align:center;margin:0 0 24px;">
        ${button('Houzeo — from $99', 'https://www.houzeo.com/?utm_source=listai&utm_medium=email&utm_campaign=followup1')}
        ${button('ListWithFreedom — from $99', 'https://www.listwithfreedom.com/?utm_source=listai&utm_medium=email&utm_campaign=followup1')}
      </div>
      <div style="text-align:center;">
        ${secondaryButton('View Your Report', `${appUrl}/report/${reportId}`)}
      </div>
    `),
  };
}

// ─── Stage 2 — Day 14: Offer Evaluation Tips ────────────────────────────────

function stage2(name: string, reportId: string, appUrl: string): EmailResult {
  return {
    subject: `${name}, how to evaluate offers like a pro`,
    html: emailWrapper(`
      <h2 style="margin:0 0 16px;color:${BRAND_NAVY};font-size:20px;">Getting Offers? Here's How to Evaluate Them</h2>
      <p style="margin:0 0 16px;color:${BRAND_SLATE};font-size:15px;line-height:1.6;">
        Hi ${name}, by now your listing may be generating interest. When offers come in, here's what to look at
        beyond just the price:
      </p>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 20px;">
        <tr><td style="padding:10px 16px;background-color:#F8FAFC;border-left:3px solid ${BRAND_ACCENT};margin-bottom:8px;border-radius:0 6px 6px 0;">
          <p style="margin:0;color:${BRAND_NAVY};font-size:14px;font-weight:600;">1. Financing Type</p>
          <p style="margin:4px 0 0;color:${BRAND_SLATE};font-size:13px;">Cash &gt; Conventional &gt; FHA/VA. Cash offers close faster and have fewer contingencies.</p>
        </td></tr>
        <tr><td style="height:8px;"></td></tr>
        <tr><td style="padding:10px 16px;background-color:#F8FAFC;border-left:3px solid ${BRAND_ACCENT};border-radius:0 6px 6px 0;">
          <p style="margin:0;color:${BRAND_NAVY};font-size:14px;font-weight:600;">2. Contingencies</p>
          <p style="margin:4px 0 0;color:${BRAND_SLATE};font-size:13px;">Fewer contingencies = less risk of the deal falling through. Watch for inspection, appraisal, and financing contingencies.</p>
        </td></tr>
        <tr><td style="height:8px;"></td></tr>
        <tr><td style="padding:10px 16px;background-color:#F8FAFC;border-left:3px solid ${BRAND_ACCENT};border-radius:0 6px 6px 0;">
          <p style="margin:0;color:${BRAND_NAVY};font-size:14px;font-weight:600;">3. Earnest Money Deposit</p>
          <p style="margin:4px 0 0;color:${BRAND_SLATE};font-size:13px;">Higher deposit = more serious buyer. 1–3% of offer price is typical.</p>
        </td></tr>
        <tr><td style="height:8px;"></td></tr>
        <tr><td style="padding:10px 16px;background-color:#F8FAFC;border-left:3px solid ${BRAND_ACCENT};border-radius:0 6px 6px 0;">
          <p style="margin:0;color:${BRAND_NAVY};font-size:14px;font-weight:600;">4. Closing Timeline</p>
          <p style="margin:4px 0 0;color:${BRAND_SLATE};font-size:13px;">Does their timeline match yours? Cash can close in 2 weeks; financed typically 30–45 days.</p>
        </td></tr>
        <tr><td style="height:8px;"></td></tr>
        <tr><td style="padding:10px 16px;background-color:#F8FAFC;border-left:3px solid ${BRAND_ACCENT};border-radius:0 6px 6px 0;">
          <p style="margin:0;color:${BRAND_NAVY};font-size:14px;font-weight:600;">5. Pre-approval Letter</p>
          <p style="margin:4px 0 0;color:${BRAND_SLATE};font-size:13px;">Always require one. A pre-qualification is not the same as a pre-approval.</p>
        </td></tr>
      </table>
      <p style="margin:0 0 20px;color:${BRAND_SLATE};font-size:14px;line-height:1.6;padding:12px 16px;background-color:#FFFBEB;border-radius:8px;border:1px solid #FDE68A;">
        <strong>Reminder:</strong> Have a licensed real estate attorney review any contract before you sign.
        Your report includes attorney referrals for your area.
      </p>
      <div style="text-align:center;">
        ${button('View Your Report', `${appUrl}/report/${reportId}`)}
      </div>
    `),
  };
}

// ─── Stage 3 — Day 30: Check-in ─────────────────────────────────────────────

function stage3(name: string, reportId: string, appUrl: string): EmailResult {
  return {
    subject: `${name}, how's your home sale going?`,
    html: emailWrapper(`
      <h2 style="margin:0 0 16px;color:${BRAND_NAVY};font-size:20px;">Quick Check-in: How's It Going?</h2>
      <p style="margin:0 0 20px;color:${BRAND_SLATE};font-size:15px;line-height:1.6;">
        Hi ${name}, it's been about a month since you received your ListAI report. We'd love to know how things
        are progressing — it helps us improve our recommendations for future sellers.
      </p>
      <p style="margin:0 0 24px;color:${BRAND_SLATE};font-size:15px;line-height:1.6;">
        Where does your sale stand?
      </p>
      <div style="text-align:center;margin:0 0 24px;">
        ${button('I Sold / Under Contract!', `${appUrl}/api/sold-status?reportId=${reportId}&status=sold`)}
        ${secondaryButton('Still on the Market', `${appUrl}/api/sold-status?reportId=${reportId}&status=active`)}
      </div>
      <p style="margin:0 0 16px;color:${BRAND_SLATE};font-size:14px;line-height:1.6;">
        If you're still on the market, don't worry — the average home takes 30–60 days to sell.
        Consider revisiting the pricing strategy in your report, and make sure your listing photos are strong.
      </p>
      <div style="text-align:center;">
        ${secondaryButton('View Your Report', `${appUrl}/report/${reportId}`)}
      </div>
    `),
  };
}

// ─── Stage 4 — Day 45: Price Adjustment Offer ───────────────────────────────

function stage4(name: string, reportId: string, appUrl: string): EmailResult {
  return {
    subject: `${name}, should you adjust your price?`,
    html: emailWrapper(`
      <h2 style="margin:0 0 16px;color:${BRAND_NAVY};font-size:20px;">Time to Revisit Your Pricing Strategy?</h2>
      <p style="margin:0 0 16px;color:${BRAND_SLATE};font-size:15px;line-height:1.6;">
        Hi ${name}, if your home is still on the market, this is a common point where a small price adjustment
        can make a big difference. Here's what the data shows:
      </p>
      <div style="padding:16px;background-color:#F8FAFC;border-radius:8px;margin:0 0 20px;">
        <p style="margin:0 0 8px;color:${BRAND_NAVY};font-size:14px;font-weight:600;">Key Facts:</p>
        <ul style="margin:0;padding:0 0 0 20px;color:${BRAND_SLATE};font-size:14px;line-height:1.8;">
          <li>Homes that reduce price within the first 45 days sell 60% faster than those that wait longer</li>
          <li>A 3–5% reduction often generates a fresh wave of buyer interest</li>
          <li>Stale listings (60+ days) get fewer showings and lower offers</li>
          <li>Seasonal timing matters — spring typically outperforms summer in most markets</li>
        </ul>
      </div>
      <p style="margin:0 0 20px;color:${BRAND_SLATE};font-size:15px;line-height:1.6;">
        Revisit the pricing section of your report to see your recommended price range and negotiation floor.
        Even a modest adjustment can re-trigger alerts on Zillow and Realtor.com.
      </p>
      <div style="text-align:center;">
        ${button('Review Your Pricing Analysis', `${appUrl}/report/${reportId}#pricing`)}
      </div>
    `),
  };
}

// ─── Stage 5 — Day 60: Referral Request (only if sold) ──────────────────────

function stage5(name: string, _reportId: string, appUrl: string): EmailResult {
  return {
    subject: `Congrats ${name}! One quick favor?`,
    html: emailWrapper(`
      <h2 style="margin:0 0 16px;color:${BRAND_NAVY};font-size:20px;">Congratulations on Your Sale!</h2>
      <p style="margin:0 0 16px;color:${BRAND_SLATE};font-size:15px;line-height:1.6;">
        Hi ${name}, we're thrilled your home sale is complete. Selling a home yourself is a huge accomplishment
        and we're glad ListAI could help along the way.
      </p>
      <p style="margin:0 0 16px;color:${BRAND_SLATE};font-size:15px;line-height:1.6;">
        We have a small favor to ask: <strong>do you know anyone else thinking about selling their home?</strong>
        A personal referral is the best compliment we can receive.
      </p>
      <div style="padding:20px;background-color:${BRAND_LIGHT};border-radius:8px;margin:0 0 24px;text-align:center;">
        <p style="margin:0 0 12px;color:${BRAND_NAVY};font-size:16px;font-weight:600;">
          Share ListAI with a friend
        </p>
        <p style="margin:0 0 16px;color:${BRAND_SLATE};font-size:14px;">
          They'll get the same AI-powered selling report that helped you sell — for just $100/mo.
        </p>
        ${button('Share ListAI', `${appUrl}?ref=${encodeURIComponent(name)}`)}
      </div>
      <p style="margin:0;color:${BRAND_SLATE};font-size:14px;line-height:1.6;">
        Thank you for trusting ListAI with one of the biggest transactions of your life. We wish you all the best
        in your next chapter.
      </p>
    `),
  };
}
