'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import ReportViewer from '@/components/ReportViewer';
import type { Report } from '@/types';

/**
 * Print-optimized view for the report. Loads the same data as /report/[id]
 * but skips the chrome (header, footer, share banner) and auto-triggers
 * the browser print dialog so the user can Save as PDF.
 *
 * ACCESS: Only agents can use this route. Homeowners are redirected back
 * to the regular report page (they view-only, no PDF export).
 */
export default function ReportPrintPage() {
  const params = useParams();
  const id = params.id as string;
  const [report, setReport] = useState<Report | null>(null);
  const [status, setStatus] = useState<'loading' | 'loaded' | 'blocked' | 'error'>('loading');

  useEffect(() => {
    if (!id) return;
    (async () => {
      try {
        const res = await fetch(`/api/report/${id}`);
        if (!res.ok) {
          setStatus('error');
          return;
        }
        const data = (await res.json()) as Report;

        // Homeowners cannot export to PDF — agent-only feature
        if (data.customer_type !== 'agent') {
          setStatus('blocked');
          return;
        }

        setReport(data);
        setStatus('loaded');

        // Give React a tick to paint, then trigger print dialog
        setTimeout(() => {
          window.print();
        }, 400);
      } catch {
        setStatus('error');
      }
    })();
  }, [id]);

  if (status === 'loading') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <p className="text-sm text-slate-500">Preparing your PDF…</p>
      </div>
    );
  }

  if (status === 'blocked') {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-white p-8 text-center">
        <h1 className="text-xl font-bold text-slate-900 mb-2">PDF export is an agent feature</h1>
        <p className="text-sm text-slate-500 max-w-md">
          Homeowner reports are view-only in the browser. Ask your subscribing
          agent if they&apos;d like to send you a PDF copy.
        </p>
      </div>
    );
  }

  if (status === 'error' || !report) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-white p-8 text-center">
        <h1 className="text-xl font-bold text-slate-900 mb-2">Couldn&apos;t load the report</h1>
        <p className="text-sm text-slate-500">Please try again.</p>
      </div>
    );
  }

  return (
    <div className="print-root bg-white">
      <style jsx global>{`
        /* Print-optimized: remove interactivity, keep semantic content */
        @media print {
          @page {
            size: letter;
            margin: 0.6in;
          }
          body {
            background: white !important;
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          /* Hide every tab-switcher and scroll UI; we'll render tabs sequentially in CSS */
          nav, button { display: none !important; }
        }
        .print-root header,
        .print-root footer,
        .print-root .no-print { display: none !important; }
      `}</style>

      <div className="max-w-4xl mx-auto px-8 py-6">
        <div className="mb-6 pb-4 border-b border-slate-200 flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold text-slate-900">
              {report.property_address}
            </h1>
            <p className="text-sm text-slate-500">
              {report.property_city}, {report.property_state} {report.property_zip}
            </p>
          </div>
          <div className="text-right">
            <p className="text-xs text-slate-400">Generated by ListAI</p>
            <p className="text-xs text-slate-400">
              {new Date(report.created_at).toLocaleDateString()}
            </p>
          </div>
        </div>

        <ReportViewer report={report} agentMode={true} accessStatus="active" />

        <div className="mt-10 pt-4 border-t border-slate-200 text-center">
          <p className="text-[10px] text-slate-400">
            listwithai.io · AI-generated real estate toolkit · Always review legal guidance with a licensed attorney.
          </p>
        </div>
      </div>
    </div>
  );
}
