import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer — ListAI',
  description: 'Important disclaimers about AI-generated real estate content from ListAI.',
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <Link
          href="/"
          className="text-sm text-slate-500 hover:text-slate-900 transition-colors mb-8 inline-block"
        >
          &larr; Back to ListAI
        </Link>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">Disclaimer</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: March 16, 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-700 leading-relaxed">
          <div className="bg-red-50 border border-red-200 rounded-lg p-5">
            <h2 className="text-lg font-semibold text-red-900 mb-3">AI-Generated Content Disclaimer</h2>
            <p className="text-red-800 text-sm leading-relaxed">
              All reports, analyses, valuations, listing copy, timelines, improvement
              recommendations, and legal document templates provided by ListAI are{' '}
              <strong>generated by artificial intelligence</strong> and are intended for{' '}
              <strong>informational and educational purposes only</strong>. This content does not
              constitute professional advice of any kind.
            </p>
          </div>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">Not Real Estate Advice</h2>
            <p>
              ListAI is <strong>not</strong> a licensed real estate broker, agent, or salesperson
              in any jurisdiction. We do not represent buyers or
              sellers in any real estate transaction. Our pricing analysis and comparable market
              data are AI-generated estimates — they are <strong>not</strong> formal appraisals
              and should not be treated as such.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">Not Legal Advice</h2>
            <p>
              ListAI is <strong>not</strong> a law firm or licensed attorney. The legal document
              templates provided in our reports are generic templates for informational purposes.
              They have <strong>not</strong> been reviewed by an attorney for your specific
              transaction. Real estate transactions involve complex legal requirements
              including title searches, lien releases, HOA estoppel letters, and mandatory
              disclosures.
            </p>
            <p className="mt-3 font-semibold">
              You MUST have all legal documents reviewed by a licensed real estate
              attorney in your state before signing or using them in any transaction.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">Not Financial or Tax Advice</h2>
            <p>
              Our reports may reference property values, potential sale proceeds, cost estimates,
              and return-on-investment projections. These are AI-generated estimates and do not
              constitute financial or tax advice. Consult a licensed CPA or financial advisor for
              tax implications related to your property sale.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">Data Accuracy</h2>
            <p>
              Our reports use data from third-party sources including property records, MLS
              comparable sales, and market statistics. While we strive for accuracy, we cannot
              guarantee that all data is current, complete, or error-free. Property values,
              market conditions, and comparable sales data change frequently.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">AI Limitations</h2>
            <p>
              Artificial intelligence models, including the ones powering ListAI, can produce
              inaccurate, incomplete, or misleading information. AI may &quot;hallucinate&quot;
              data points or make assumptions that don&apos;t apply to your specific situation.
              Always verify critical information (especially pricing, legal terms, and timelines)
              with qualified professionals.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">State-Specific Notice</h2>
            <p>
              Real estate law varies by state and has specific requirements for FSBO (For Sale By Owner)
              transactions, including but not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Mandatory seller disclosure requirements (your state&apos;s specific disclosure requirements)</li>
              <li>Lead-based paint disclosure for homes built before 1978</li>
              <li>HOA/condo association disclosure requirements</li>
              <li>Title insurance and closing procedures</li>
              <li>Documentary stamp tax and recording fees</li>
              <li>Radon gas disclosure</li>
            </ul>
            <p className="mt-3">
              ListAI reports may not cover all legal requirements applicable to your specific
              property and transaction. Consult a licensed real estate attorney in your state.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">No Guarantees</h2>
            <p>
              ListAI makes no guarantees regarding the sale of your property, the accuracy of
              price estimates, the timeline for selling, or the effectiveness of any
              recommendations. Real estate outcomes depend on many factors beyond the scope of
              our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">Contact</h2>
            <p>
              If you have questions about this disclaimer, contact us at{' '}
              <a href="mailto:evangelos@univentureprop.com" className="text-blue-600 hover:underline">
                evangelos@univentureprop.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
